package com.cukkoo.freecamera.gui;

import com.cukkoo.freecamera.FreeCameraClient;import com.cukkoo.freecamera.api.CameraMode;import com.cukkoo.freecamera.collision.CameraCollisionMode;import com.cukkoo.freecamera.config.*;import com.cukkoo.freecamera.follow.FollowProfile;import net.minecraft.client.gui.GuiGraphicsExtractor;import net.minecraft.client.gui.components.*;import net.minecraft.client.gui.screens.Screen;import net.minecraft.network.chat.Component;import java.util.*;import java.util.function.*;
import com.cukkoo.freecamera.recording.CameraRecordingStorage;import com.cukkoo.freecamera.path.*;import java.io.IOException;import java.nio.file.Path;

public final class CameraSettingsScreen extends Screen{
 private static final String[] TABS={"General","Camera","Follow","Visuals","Studio","Advanced"};
 private static final String[][] TAB_FIELDS={{"lastMode","rememberLastMode","radialHoldMillis","radialDeadZone","mouseSensitivity","preset"},{"speedPreset","customSpeed","acceleration","deceleration","cinematicAcceleration","cinematicDeceleration","orbitRadius","orbitSensitivity","freeCollision","orbitCollision","rollSpeed","rollSmoothing","cinematicRollSmoothing","zoomMultiplier","zoomSmoothing","cinematicZoomSmoothing"},{"followProfile","followDistance","followHeight","followLateral","followPositionSmoothing","followRotationSmoothing","followCollision","followRange","followPlayers","followMobs","followBoats","followMinecarts","followArmorStands","followVehicles"},{"hideHand","hideCrosshair","hideHud","suppressViewBobbing","suppressHurtCamera","statusOverlay","controlHints","hideStatusWithDebug","letterbox","letterboxSize","statusPosition"},{"playbackCollision","defaultPlaybackSpeed"},{"collisionMargin","maximumFrameTime","movementSubsteps","recordingRate","recordingMaxSeconds","maximumRecordingSamples","maximumPathKeyframes","pathInterpolation","pathEasing","defaultPlaybackSpeed","playbackCollisionMode"}};
 private final Screen parent;private final FreeCameraConfigManager manager;private FreeCameraConfig original,working;private int tab,scroll;private boolean dirty;private CameraPreset pendingPreset;private String presetPreview="";
 private boolean studioPaths;private List<CameraRecordingStorage.Metadata> recordings=List.of();private List<CameraPathStorage.Metadata> paths=List.of();private int selectedRecording=-1,selectedPath=-1;private String studioStatus="";private boolean confirmRecordingDelete,confirmPathDelete;
 private String studioName="";
 private String settingsStatus="";
 private boolean studioLoaded;
 private final Map<Integer,Component> visibleLabels=new HashMap<>();
 private int panelLeft,panelRight,panelTop,panelBottom,contentTop,contentBottom,controlLeft,controlWidth,labelLeft;private boolean narrowLayout;
 private static final int ROW_HEIGHT=23,SECTION_HEIGHT=18;
 private static final int[][] SECTION_STARTS={{0,2,5},{0,4,6,8,10,13},{0,1,4,6,9},{0,2,3,8},{},{0,3,6,9}};
 private static final String[][] SECTION_TITLES={{"Camera Defaults","Radial Menu","Presets"},{"Movement","Cinematic Motion","Orbit","Collision","Roll","Zoom"},{"Profile","Framing","Smoothing","Target & Collision","Target Filters"},{"First-person View","HUD","Camera Effects","Letterbox"},{},{"Motion & Collision","Recording","Paths","Playback"}};
 private static final Component[][] SECTION_LABELS=createSectionLabels();
 private Component footerStatus=Component.empty();private Object cachedFollowEntity;private String cachedStudioStatus="";private int footerStatusColor=0xFFAAAAAA;
 public CameraSettingsScreen(Screen parent,FreeCameraConfigManager manager){super(Component.translatable("screen.free-camera.settings"));this.parent=parent;this.manager=manager;original=FreeCameraConfigManager.copy(manager.config());working=FreeCameraConfigManager.copy(original);}
 @Override protected void init(){panelLeft=Math.max(10,(width-Math.min(760,width-20))/2);panelRight=width-panelLeft;panelTop=Math.max(8,(height-Math.min(430,height-16))/2);panelBottom=height-panelTop;contentTop=panelTop+55;contentBottom=panelBottom-46;labelLeft=panelLeft+18;int inner=panelRight-panelLeft-36;narrowLayout=inner<520;controlWidth=narrowLayout?inner:Math.clamp(inner/2,150,292);controlLeft=narrowLayout?labelLeft:panelRight-18-controlWidth;visibleLabels.clear();int tw=Math.max(48,(panelRight-panelLeft-24)/6),start=panelLeft+12;for(int i=0;i<6;i++){int selected=i;Button tabButton=Button.builder(ui(TABS[i]),b->{tab=selected;scroll=0;rebuildWidgets();}).bounds(start+i*tw,panelTop+25,tw-2,18).build();tabButton.active=i!=tab;addRenderableWidget(tabButton);}buildTab();refreshFooterStatus();bottomButtons();}
 private void buildTab(){switch(tab){case 0->general();case 1->camera();case 2->follow();case 3->visuals();case 4->studio();case 5->advanced();}}
 private int rowHeight(){return narrowLayout&&tab!=4?34:ROW_HEIGHT;}private int y(int row){return contentTop+(row-scroll)*rowHeight()+sectionOffset(row);}private int widgetY(int row){return y(row)+(narrowLayout&&tab!=4?13:0);}private int labelY(int row){return y(row)+(narrowLayout&&tab!=4?0:5);}private int sectionOffset(int row){int count=0;for(int start:SECTION_STARTS[tab])if(start<=row)count++;return count*SECTION_HEIGHT;}private boolean show(int row){return y(row)>=contentTop&&widgetY(row)<=contentBottom-18;}
 private void add(int row,AbstractWidget widget){if(show(row))addRenderableWidget(widget);}
 private void bool(int row,String label,BooleanSupplier get,Consumer<Boolean> set){if(!show(row))return;visibleLabels.put(row,ui(label));CycleButton<Boolean>w=CycleButton.onOffBuilder(get.getAsBoolean()).create(controlLeft,widgetY(row),controlWidth,18,Component.empty(),(b,v)->{set.accept(v);markDirty();});w.setTooltip(Tooltip.create(ui("Configure "+label)));addRenderableWidget(w);}
 private <T>void cycle(int row,String label,T current,List<T>values,Consumer<T>set){if(!show(row))return;visibleLabels.put(row,ui(label));CycleButton<T>w=CycleButton.builder(CameraSettingsScreen::humanName,current).withValues(values).create(controlLeft,widgetY(row),controlWidth,18,Component.empty(),(b,v)->{set.accept(v);markDirty();});w.setTooltip(Tooltip.create(ui("Select "+label)));addRenderableWidget(w);}
 private void slider(int row,String label,double min,double max,DoubleSupplier get,DoubleConsumer set){if(show(row)){visibleLabels.put(row,ui(label));addRenderableWidget(new ConfigSlider(controlLeft,widgetY(row),controlWidth,ui(label),ui("Adjust "+label),min,max,get,v->{set.accept(v);markDirty();}));}}
 private void general(){cycle(0,"Preferred Camera Mode",working.lastMode,List.of(CameraMode.values()),v->working.lastMode=v);bool(1,"Remember Last-used Mode",()->working.rememberLastMode,v->working.rememberLastMode=v);slider(2,"Radial Hold (ms)",150,1500,()->working.radialHoldMillis,v->working.radialHoldMillis=Math.round(v));slider(3,"Radial Dead Zone",4,80,()->working.radialDeadZone,v->working.radialDeadZone=v);slider(4,"Mouse Sensitivity",.1,5,()->working.mouseSensitivity,v->working.mouseSensitivity=v);cycle(5,"Preset",CameraPreset.valueOf(working.preset),List.of(CameraPreset.values()),v->{pendingPreset=v;presetPreview=preview(v);});add(6,button("Confirm Preset",b->{if(pendingPreset!=null){pendingPreset.apply(working);pendingPreset=null;markDirty();rebuildWidgets();}},width/2-150,y(6),300));}
 private void camera(){cycle(0,"Speed Preset",working.speedPreset,List.of("PRECISE","SLOW","NORMAL","FAST","FLYBY","CUSTOM"),v->working.speedPreset=v);slider(1,"Custom Speed",.05,128,()->working.customSpeed,v->{working.customSpeed=v;working.speedPreset="CUSTOM";});slider(2,"Acceleration",.1,100,()->working.acceleration,v->{working.acceleration=v;working.speedPreset="CUSTOM";});slider(3,"Deceleration",.1,100,()->working.deceleration,v->{working.deceleration=v;working.speedPreset="CUSTOM";});slider(4,"Cinematic Acceleration",.1,100,()->working.cinematicAcceleration,v->working.cinematicAcceleration=v);slider(5,"Cinematic Deceleration",.1,100,()->working.cinematicDeceleration,v->working.cinematicDeceleration=v);slider(6,"Orbit Radius",1,64,()->working.orbitRadius,v->working.orbitRadius=v);slider(7,"Orbit Sensitivity",.1,5,()->working.orbitSensitivity,v->working.orbitSensitivity=v);cycle(8,"Free Collision",working.freeCollision,List.of(CameraCollisionMode.values()),v->working.freeCollision=v);cycle(9,"Orbit Collision",working.orbitCollision,List.of(CameraCollisionMode.values()),v->working.orbitCollision=v);slider(10,"Roll Speed",1,360,()->working.rollSpeed,v->working.rollSpeed=v);slider(11,"Responsive Roll Smoothing",.1,40,()->working.rollSmoothing,v->working.rollSmoothing=v);slider(12,"Cinematic Roll Smoothing",.1,40,()->working.cinematicRollSmoothing,v->working.cinematicRollSmoothing=v);slider(13,"Zoom Multiplier",1,10,()->working.zoomMultiplier,v->working.zoomMultiplier=v);slider(14,"Responsive Zoom Smoothing",.1,40,()->working.zoomSmoothing,v->working.zoomSmoothing=v);slider(15,"Cinematic Zoom Smoothing",.1,40,()->working.cinematicZoomSmoothing,v->working.cinematicZoomSmoothing=v);}
 private void follow(){cycle(0,"Follow Profile",working.followProfile,List.of(FollowProfile.values()),v->working.followProfile=v);slider(1,"Distance",1,64,()->working.followDistance,v->working.followDistance=v);slider(2,"Height Offset",-16,32,()->working.followHeight,v->working.followHeight=v);slider(3,"Lateral Offset",-32,32,()->working.followLateral,v->working.followLateral=v);slider(4,"Position Smoothing",.1,40,()->working.followPositionSmoothing,v->working.followPositionSmoothing=v);slider(5,"Rotation Smoothing",.1,40,()->working.followRotationSmoothing,v->working.followRotationSmoothing=v);cycle(6,"Collision",working.followCollision,List.of(CameraCollisionMode.values()),v->working.followCollision=v);slider(7,"Selection Range",8,256,()->working.followRange,v->working.followRange=v);add(8,button("Follow Local Player",b->FreeCameraClient.followLocalPlayer(),width/2-150,y(8),148));add(8,button("Clear Target → Free",b->FreeCameraClient.clearFollowTarget(),width/2+2,y(8),148));bool(9,"Players",()->working.followPlayers,v->working.followPlayers=v);bool(10,"Mobs",()->working.followMobs,v->working.followMobs=v);bool(11,"Boats",()->working.followBoats,v->working.followBoats=v);bool(12,"Minecarts",()->working.followMinecarts,v->working.followMinecarts=v);bool(13,"Armor Stands",()->working.followArmorStands,v->working.followArmorStands=v);bool(14,"Other Vehicles",()->working.followVehicles,v->working.followVehicles=v);}
 private void visuals(){bool(0,"Hide Hand",()->working.hideHand,v->working.hideHand=v);bool(1,"Hide Crosshair",()->working.hideCrosshair,v->working.hideCrosshair=v);bool(2,"Hide Complete HUD",()->working.hideHud,v->working.hideHud=v);bool(3,"Suppress View Bobbing",()->working.suppressViewBobbing,v->working.suppressViewBobbing=v);bool(4,"Suppress Hurt-camera Shake",()->working.suppressHurtCamera,v->working.suppressHurtCamera=v);bool(5,"Show Status Overlay",()->working.statusOverlay,v->working.statusOverlay=v);bool(6,"Show Control Hints",()->working.controlHints,v->working.controlHints=v);bool(7,"Hide Status With Debug",()->working.hideStatusWithDebug,v->working.hideStatusWithDebug=v);bool(8,"Cinematic Letterbox",()->working.letterbox,v->working.letterbox=v);slider(9,"Letterbox Size",0,.3,()->working.letterboxSize,v->working.letterboxSize=v);cycle(10,"Status Position",working.statusPosition,List.of("TOP_LEFT","TOP_RIGHT","BOTTOM_LEFT","BOTTOM_RIGHT"),v->working.statusPosition=v);}
 private void studio(){
  if(!studioLoaded)refreshStudio();
  add(0,button(studioPaths?"Show Recordings":"Show Paths",b->{studioPaths=!studioPaths;scroll=0;refreshStudio();rebuildWidgets();},width/2-150,y(0),300));
  if(show(1)){EditBox name=new EditBox(font,width/2-150,y(1),210,20,Component.literal("Name"));name.setValue(studioName);name.setHint(Component.literal("Recording or path name"));name.setResponder(v->studioName=v);addRenderableWidget(name);addRenderableWidget(button("Refresh",b->{refreshStudio();rebuildWidgets();},width/2+64,y(1),86));}
  if(studioPaths)pathStudio();else recordingStudio();
 }
 private void recordingStudio(){
  for(int i=0;i<recordings.size();i++){int index=i;var m=recordings.get(i);String date=java.time.Instant.ofEpochMilli(m.modified().toMillis()).atZone(java.time.ZoneId.systemDefault()).toLocalDate().toString();String label=(i==selectedRecording?"> ":"")+m.name()+" | "+fmt(m.duration())+"s | "+m.sampleCount()+" @ "+fmt(m.sampleRate())+"Hz | "+date+(m.corrupt()?" | CORRUPT":"");add(2+i,button(label,b->{selectedRecording=index;studioName=m.name();confirmRecordingDelete=false;rebuildWidgets();},width/2-150,y(2+i),300));}
  int r=2+recordings.size();add(r,enabledButton("Start Recording",b->FreeCameraClient.startRecording(),width/2-150,y(r),148,FreeCameraClient.activeSession()!=null&&!FreeCameraClient.recordingController().isRecording()));add(r,enabledButton("Stop & Keep",b->FreeCameraClient.stopRecording(),width/2+2,y(r),148,FreeCameraClient.recordingController().isRecording()));
  var chosen=selectedRecording();add(++r,enabledButton("Play Selected",b->loadAndPlayRecording(),width/2-150,y(r),148,chosen!=null&&!chosen.corrupt()&&FreeCameraClient.activeSession()!=null));add(r,enabledButton("Pause / Resume",b->toggleRecordingPause(),width/2+2,y(r),148,FreeCameraClient.recordingController().playback().isPlaying()));
  add(++r,enabledButton("Stop Playback",b->FreeCameraClient.stopPlayback(),width/2-150,y(r),148,FreeCameraClient.recordingController().playback().isPlaying()));add(r,enabledButton("Save Last",b->saveLastRecording(),width/2+2,y(r),148,FreeCameraClient.recordingController().last()!=null));
  add(++r,enabledButton("Rename Selected",b->renameRecording(),width/2-150,y(r),148,chosen!=null&&!chosen.corrupt()));add(r,enabledButton("Duplicate Selected",b->duplicateRecording(),width/2+2,y(r),148,chosen!=null&&!chosen.corrupt()));
  add(++r,enabledButton(confirmRecordingDelete?"CONFIRM DELETE":"Delete Selected",b->{if(confirmRecordingDelete)deleteRecording();else{confirmRecordingDelete=true;rebuildWidgets();}},width/2-150,y(r),300,chosen!=null));
  bool(++r,"Loop Playback",()->FreeCameraClient.recordingController().playback().isLoop(),v->FreeCameraClient.recordingController().playback().setLoop(v));
  bool(++r,"Reverse Playback",()->FreeCameraClient.recordingController().playback().isReverse(),v->FreeCameraClient.recordingController().playback().setReverse(v));
  bool(++r,"Playback Collision",()->working.playbackCollision,v->working.playbackCollision=v);slider(++r,"Playback Speed",.1,4,()->working.defaultPlaybackSpeed,v->{working.defaultPlaybackSpeed=v;FreeCameraClient.recordingController().playback().setSpeed(v);});
 }
 private void pathStudio(){
  for(int i=0;i<paths.size();i++){int index=i;var m=paths.get(i);String label=(i==selectedPath?"> ":"")+m.name()+" | "+m.keyframes()+" keyframes | "+fmt(m.duration())+"s | "+m.interpolation()+(m.corrupt()?" | CORRUPT":"");add(2+i,button(label,b->selectPath(index),width/2-150,y(2+i),300));}
  var chosen=selectedPath();int r=2+paths.size();add(r,button("New Path",b->{if(FreeCameraClient.studioState().dirty()){studioStatus="Save or discard the current path first";return;}FreeCameraClient.newPath();},width/2-150,y(r),148));add(r,enabledButton("Load Selected",b->loadPath(),width/2+2,y(r),148,chosen!=null&&!chosen.corrupt()));
  add(++r,button("Save Path",b->savePath(),width/2-150,y(r),148));add(r,button("Discard Changes",b->discardPath(),width/2+2,y(r),148));
  add(++r,enabledButton("Rename Selected",b->renamePath(),width/2-150,y(r),148,chosen!=null&&!chosen.corrupt()));add(r,enabledButton("Duplicate Selected",b->duplicatePath(),width/2+2,y(r),148,chosen!=null&&!chosen.corrupt()));
  add(++r,enabledButton(confirmPathDelete?"CONFIRM DELETE":"Delete Selected",b->{if(confirmPathDelete)deletePath();else{confirmPathDelete=true;rebuildWidgets();}},width/2-150,y(r),300,chosen!=null));
  add(++r,enabledButton("Add Current Pose",b->FreeCameraClient.addCurrentKeyframe(),width/2-150,y(r),148,FreeCameraClient.activeSession()!=null));add(r,enabledButton("Replace Selected",b->replaceKeyframe(),width/2+2,y(r),148,FreeCameraClient.activeSession()!=null&&FreeCameraClient.studioState().selected()>=0));
  int selected=FreeCameraClient.studioState().selected();add(++r,enabledButton("Duplicate Keyframe",b->duplicateKeyframe(),width/2-150,y(r),148,selected>=0));add(r,enabledButton("Delete Keyframe",b->deleteKeyframe(),width/2+2,y(r),148,selected>=0));
  add(++r,enabledButton("Move Keyframe Up",b->moveKeyframe(-1),width/2-150,y(r),148,selected>0));add(r,enabledButton("Move Keyframe Down",b->moveKeyframe(1),width/2+2,y(r),148,selected>=0&&selected<FreeCameraClient.studioState().path().size()-1));
  var path=FreeCameraClient.studioState().path();if(path.size()>0){int s=FreeCameraClient.studioState().selected();if(s<0){FreeCameraClient.studioState().select(0);s=0;}var k=path.get(s);slider(++r,"Duration to Next",0,60,()->k.duration(),v->replaceTiming(v,k.hold(),k.easing()));slider(++r,"Hold Duration",0,60,()->k.hold(),v->replaceTiming(k.duration(),v,k.easing()));cycle(++r,"Easing",k.easing(),List.of(PathEasing.values()),v->replaceTiming(k.duration(),k.hold(),v));}
  cycle(++r,"Interpolation",path.interpolation(),List.of(PathInterpolation.values()),v->{path.setInterpolation(v);FreeCameraClient.studioState().markDirty();});
  for(int i=0;i<path.size();i++){int index=i;var frame=path.get(i);String label="#"+(i+1)+"  "+fmt(frame.x())+","+fmt(frame.y())+","+fmt(frame.z())+" | yaw "+fmt(frame.yaw())+" pitch "+fmt(frame.pitch())+" roll "+fmt(frame.roll())+" zoom "+fmt(frame.zoom())+" | "+fmt(frame.duration())+"s + hold "+fmt(frame.hold())+" | "+frame.easing();add(++r,button(label,b->{FreeCameraClient.studioState().select(index);rebuildWidgets();},width/2-150,y(r),300));}
  add(++r,enabledButton("Play Path",b->playStudioPath(),width/2-150,y(r),148,path.size()>=2&&(FreeCameraClient.activeSession()!=null||minecraft.level!=null)));add(r,enabledButton("Pause / Resume",b->togglePathPause(),width/2+2,y(r),148,FreeCameraClient.pathController().isPlaying()));add(++r,enabledButton("Stop Path",b->FreeCameraClient.stopPath(),width/2-150,y(r),300,FreeCameraClient.pathController().isPlaying()));
  bool(++r,"Loop",()->FreeCameraClient.pathController().isLoop(),v->FreeCameraClient.pathController().setLoop(v));bool(++r,"Reverse",()->FreeCameraClient.pathController().isReverse(),v->FreeCameraClient.pathController().setReverse(v));bool(++r,"Ping-pong",()->FreeCameraClient.pathController().isPingPong(),v->FreeCameraClient.pathController().setPingPong(v));bool(++r,"Playback Collision",()->working.playbackCollision,v->working.playbackCollision=v);slider(++r,"Playback Speed",.1,4,()->working.defaultPlaybackSpeed,v->{working.defaultPlaybackSpeed=v;FreeCameraClient.pathController().setSpeed(v);});
 }
 private void refreshStudio(){studioLoaded=true;try{recordings=FreeCameraClient.recordingStorage().listMetadata(working.maximumRecordingSamples);paths=FreeCameraClient.pathStorage().listMetadata(working.maximumPathKeyframes);studioStatus="";}catch(IOException e){studioStatus="Refresh failed: "+e.getMessage();}}
 private String requiredName(){String s=studioName==null?"":studioName.trim();if(s.isEmpty()){studioStatus="A non-empty name is required";return null;}return s;}
 private CameraRecordingStorage.Metadata selectedRecording(){return selectedRecording>=0&&selectedRecording<recordings.size()?recordings.get(selectedRecording):null;}
 private CameraPathStorage.Metadata selectedPath(){return selectedPath>=0&&selectedPath<paths.size()?paths.get(selectedPath):null;}
 private void loadAndPlayRecording(){var m=selectedRecording();if(m==null||m.corrupt())return;try{var rec=FreeCameraClient.recordingStorage().load(m.file(),working.maximumRecordingSamples);FreeCameraClient.recordingController().setLast(rec);FreeCameraClient.recordingController().playLast();}catch(IOException e){studioStatus=e.getMessage();}}
 private void toggleRecordingPause(){var p=FreeCameraClient.recordingController().playback();if(p.isPaused())p.resume();else p.pause();}
 private void saveLastRecording(){var rec=FreeCameraClient.recordingController().last();String name=requiredName();if(rec==null){studioStatus="No completed recording to save";return;}if(name==null)return;try{rec.setName(name);FreeCameraClient.recordingStorage().save(rec,name);refreshStudio();rebuildWidgets();}catch(IOException e){studioStatus=e.getMessage();}}
 private void renameRecording(){var m=selectedRecording();String name=requiredName();if(m==null||name==null)return;try{FreeCameraClient.recordingStorage().rename(m.file(),name);refreshStudio();rebuildWidgets();}catch(IOException e){studioStatus=e.getMessage();}}
 private void duplicateRecording(){var m=selectedRecording();String name=requiredName();if(m==null||name==null)return;try{FreeCameraClient.recordingStorage().duplicate(m.file(),name);refreshStudio();rebuildWidgets();}catch(IOException e){studioStatus=e.getMessage();}}
 private void deleteRecording(){var m=selectedRecording();if(m==null)return;try{FreeCameraClient.recordingStorage().delete(m.file());selectedRecording=-1;confirmRecordingDelete=false;refreshStudio();rebuildWidgets();}catch(IOException e){studioStatus=e.getMessage();}}
 private void selectPath(int index){if(FreeCameraClient.studioState().dirty()){studioStatus="Save or discard current path changes first";return;}selectedPath=index;confirmPathDelete=false;var m=selectedPath();if(m!=null)studioName=m.name();rebuildWidgets();}
 private void loadPath(){var m=selectedPath();if(m==null||m.corrupt())return;if(FreeCameraClient.studioState().dirty()){studioStatus="Save or discard current path changes first";return;}try{FreeCameraClient.studioState().load(FreeCameraClient.pathStorage().load(m.file(),working.maximumPathKeyframes),m.file());studioName=m.name();rebuildWidgets();}catch(IOException e){studioStatus=e.getMessage();}}
 private void savePath(){String name=requiredName();if(name==null)return;try{var state=FreeCameraClient.studioState();state.path().setName(name);Path file=FreeCameraClient.pathStorage().save(state.path(),name,state.file()!=null&&state.file().getFileName().toString().equals(com.cukkoo.freecamera.recording.CameraRecordingStorage.sanitize(name)+".json"));state.setFile(file);refreshStudio();rebuildWidgets();}catch(IOException e){studioStatus=e.getMessage();}}
 private void discardPath(){var state=FreeCameraClient.studioState();if(state.file()==null){state.discardNew();rebuildWidgets();return;}try{state.load(FreeCameraClient.pathStorage().load(state.file(),working.maximumPathKeyframes),state.file());rebuildWidgets();}catch(IOException e){studioStatus=e.getMessage();}}
 private void renamePath(){var m=selectedPath();String name=requiredName();if(m==null||name==null)return;try{FreeCameraClient.pathStorage().rename(m.file(),name);refreshStudio();rebuildWidgets();}catch(IOException e){studioStatus=e.getMessage();}}
 private void duplicatePath(){var m=selectedPath();String name=requiredName();if(m==null||name==null)return;try{FreeCameraClient.pathStorage().duplicate(m.file(),name);refreshStudio();rebuildWidgets();}catch(IOException e){studioStatus=e.getMessage();}}
 private void deletePath(){var m=selectedPath();if(m==null)return;try{FreeCameraClient.pathStorage().delete(m.file());selectedPath=-1;confirmPathDelete=false;refreshStudio();rebuildWidgets();}catch(IOException e){studioStatus=e.getMessage();}}
 private void replaceKeyframe(){var state=FreeCameraClient.studioState();int i=state.selected();var session=FreeCameraClient.activeSession();if(i<0||session==null)return;var old=state.path().get(i);var p=session.renderedPose();double current=FreeCameraClient.currentRoll(),roll=i>0?state.path().get(i-1).roll()+com.cukkoo.freecamera.roll.CameraRollState.normalizeDegrees(current-com.cukkoo.freecamera.roll.CameraRollState.normalizeDegrees(state.path().get(i-1).roll())):current;state.path().replace(i,new CameraKeyframe(p.x(),p.y(),p.z(),p.yaw(),p.pitch(),roll,FreeCameraClient.currentZoom(),old.duration(),old.easing(),old.hold()));state.markDirty();}
 private void duplicateKeyframe(){var s=FreeCameraClient.studioState();if(s.selected()>=0){s.path().duplicate(s.selected());s.select(s.selected()+1);s.markDirty();rebuildWidgets();}}
 private void deleteKeyframe(){var s=FreeCameraClient.studioState();if(s.selected()>=0){s.path().remove(s.selected());s.select(Math.min(s.selected(),s.path().size()-1));s.markDirty();rebuildWidgets();}}
 private void moveKeyframe(int delta){var s=FreeCameraClient.studioState();int from=s.selected(),to=from+delta;if(from>=0&&to>=0&&to<s.path().size()){s.path().move(from,to);s.select(to);s.markDirty();rebuildWidgets();}}
 private void replaceTiming(double duration,double hold,PathEasing easing){var s=FreeCameraClient.studioState();int i=s.selected();if(i<0)return;var k=s.path().get(i);s.path().replace(i,new CameraKeyframe(k.x(),k.y(),k.z(),k.yaw(),k.pitch(),k.roll(),k.zoom(),duration,easing,hold));s.markDirty();}
 private void togglePathPause(){var p=FreeCameraClient.pathController();if(p.isPaused())p.resume();else p.pause();}
 private void playStudioPath(){if(FreeCameraClient.activeSession()==null){if(!apply())return;minecraft.setScreen(parent);}FreeCameraClient.playPath();}
 private static String fmt(double v){return String.format(java.util.Locale.ROOT,"%.1f",v);}private double selectedSpeed(){if("CUSTOM".equals(working.speedPreset))return working.customSpeed;try{return com.cukkoo.freecamera.motion.SpeedPreset.valueOf(working.speedPreset).blocksPerSecond();}catch(IllegalArgumentException e){return 4;}}
 private void advanced(){slider(0,"Collision Safety Margin",.001,.1,()->working.collisionMargin,v->working.collisionMargin=v);slider(1,"Maximum Frame Time",.05,.5,()->working.maximumFrameTime,v->working.maximumFrameTime=v);slider(2,"Movement Substeps",1,20,()->working.movementSubsteps,v->working.movementSubsteps=(int)Math.round(v));slider(3,"Recording Sample Rate",10,120,()->working.recordingRate,v->working.recordingRate=(int)Math.round(v));slider(4,"Recording Maximum Seconds",10,3600,()->working.recordingMaxSeconds,v->working.recordingMaxSeconds=(int)Math.round(v));slider(5,"Maximum Recording Samples",100,432000,()->working.maximumRecordingSamples,v->working.maximumRecordingSamples=(int)Math.round(v));slider(6,"Maximum Path Keyframes",2,4096,()->working.maximumPathKeyframes,v->working.maximumPathKeyframes=(int)Math.round(v));cycle(7,"Path Interpolation",working.pathInterpolation,List.of("LINEAR","SMOOTH"),v->working.pathInterpolation=v);cycle(8,"Path Easing",working.pathEasing,List.of("LINEAR","SMOOTH","CINEMATIC"),v->working.pathEasing=v);slider(9,"Default Playback Speed",.1,4,()->working.defaultPlaybackSpeed,v->working.defaultPlaybackSpeed=v);cycle(10,"Playback Collision Mode",working.playbackCollisionMode,List.of("OFF","SOFT","VANILLA"),v->working.playbackCollisionMode=v);add(11,button("Open Config Folder",b->FreeCameraClient.openConfigFolder(),width/2-150,y(11),300));add(12,button("Restore Advanced Defaults",b->{FreeCameraConfig d=FreeCameraConfigDefaults.create();for(String name:TAB_FIELDS[5])try{var f=FreeCameraConfig.class.getField(name);f.set(working,f.get(d));}catch(ReflectiveOperationException ignored){}markDirty();rebuildWidgets();},width/2-150,y(12),300));}
 private static Component ui(String fallback){String key=fallback.toLowerCase(java.util.Locale.ROOT).replaceAll("[^a-z0-9]+","_").replaceAll("^_|_$","");return Component.translatableWithFallback("gui.free-camera."+key,fallback);}
 private static Component[][] createSectionLabels(){Component[][] result=new Component[SECTION_TITLES.length][];for(int i=0;i<SECTION_TITLES.length;i++){result[i]=new Component[SECTION_TITLES[i].length];for(int j=0;j<SECTION_TITLES[i].length;j++)result[i][j]=ui(SECTION_TITLES[i][j]);}return result;}
 private static <T>Component humanName(T value){if(value==null)return Component.empty();if(value==CameraMode.FREE_CAMERA)return ui("Free Camera");String raw=value instanceof Enum<?>e?e.name():String.valueOf(value);StringBuilder text=new StringBuilder(raw.length());boolean upper=true;for(int i=0;i<raw.length();i++){char c=raw.charAt(i);if(c=='_'){text.append(' ');upper=true;}else{text.append(upper?Character.toUpperCase(c):Character.toLowerCase(c));upper=false;}}return Component.literal(text.toString());}
 private Button button(String text,Button.OnPress action,int x,int y,int w){Button b=Button.builder(ui(text),action).bounds(x,y,w,20).build();b.setTooltip(Tooltip.create(ui(text)));return b;}
 private Button enabledButton(String text,Button.OnPress action,int x,int y,int w,boolean active){Button b=button(text,action,x,y,w);b.active=active;return b;}
 private void bottomButtons(){int gap=4,w=Math.max(58,Math.min(82,(panelRight-panelLeft-32-gap*4)/5)),total=w*5+gap*4,x=(width-total)/2,y=panelBottom-31;addRenderableWidget(button("Reset Tab",b->{resetTab();rebuildWidgets();},x,y,w));addRenderableWidget(button("Reset All",b->{working=FreeCameraConfigDefaults.create();markDirty();rebuildWidgets();},x+(w+gap),y,w));addRenderableWidget(button("Apply",b->apply(),x+2*(w+gap),y,w));addRenderableWidget(button("Cancel",b->cancel(),x+3*(w+gap),y,w));addRenderableWidget(button("Done",b->{if(apply())minecraft.setScreen(parent);},x+4*(w+gap),y,w));}
 private boolean apply(){FreeCameraConfig previous=FreeCameraConfigManager.copy(manager.config());try{FreeCameraConfigValidator.validate(working);manager.replace(FreeCameraConfigManager.copy(working));manager.save();FreeCameraClient.applyConfiguration();original=FreeCameraConfigManager.copy(working);dirty=false;settingsStatus="Settings applied";return true;}catch(Exception failure){manager.replace(previous);FreeCameraClient.applyConfiguration();settingsStatus="Could not save settings: "+failure.getMessage();return false;}}
 private void cancel(){if(FreeCameraClient.studioState().dirty()){studioStatus="Unsaved path: Save or Discard Changes before closing";tab=4;rebuildWidgets();return;}manager.replace(FreeCameraConfigManager.copy(original));FreeCameraClient.applyConfiguration();minecraft.setScreen(parent);} @Override public void onClose(){cancel();}
 private void resetTab(){FreeCameraConfig defaults=FreeCameraConfigDefaults.create();for(String name:TAB_FIELDS[tab])try{var f=FreeCameraConfig.class.getField(name);f.set(working,f.get(defaults));}catch(ReflectiveOperationException ignored){}markDirty();}
 private void markDirty(){FreeCameraConfigValidator.validate(working);dirty=true;refreshFooterStatus();}
 private void refreshFooterStatus(){footerStatusColor=0xFFAAAAAA;if(tab==1)footerStatus=Component.literal("Selected speed: "+fmt(selectedSpeed())+" blocks/second");else if(tab==2){cachedFollowEntity=FreeCameraClient.followTargetEntity();footerStatus=Component.literal("Current Target: ").append(FreeCameraClient.followTargetComponent());}else if(tab==4&&!studioStatus.isEmpty()){cachedStudioStatus=studioStatus;footerStatus=Component.literal(studioStatus);footerStatusColor=0xFFFF7777;}else if(tab==5){footerStatus=ui("Advanced settings can affect motion quality and performance.");footerStatusColor=0xFFFFAA55;}else if(!settingsStatus.isEmpty()){footerStatus=Component.literal(settingsStatus);footerStatusColor=0xFF77FF77;}else if(!presetPreview.isEmpty())footerStatus=Component.literal(presetPreview);else footerStatus=Component.empty();}
 private String preview(CameraPreset p){FreeCameraConfig proposed=FreeCameraConfigManager.copy(working);p.apply(proposed);StringBuilder s=new StringBuilder();for(String f:p.changedFields())try{var field=FreeCameraConfig.class.getField(f);s.append(f).append(": ").append(field.get(working)).append(" → ").append(field.get(proposed)).append("; ");}catch(Exception ignored){}return s.toString();}
 private int rowCount(){if(tab==4){if(!studioPaths)return recordings.size()+16;return paths.size()+FreeCameraClient.studioState().path().size()+25;}return (new int[]{7,16,15,11,1,13})[tab];}
 @Override public boolean mouseScrolled(double x,double y,double horizontal,double vertical){if(x<panelLeft||x>panelRight||y<contentTop||y>contentBottom)return super.mouseScrolled(x,y,horizontal,vertical);int visible=Math.max(1,(contentBottom-contentTop)/rowHeight()-2),maximum=Math.max(0,rowCount()-visible);int next=Math.clamp(scroll-(int)Math.signum(vertical),0,maximum);if(next!=scroll){scroll=next;rebuildWidgets();return true;}return super.mouseScrolled(x,y,horizontal,vertical);}
 @Override public void extractBackground(GuiGraphicsExtractor g,int mx,int my,float d){super.extractBackground(g,mx,my,d);g.fill(panelLeft,panelTop,panelRight,panelBottom,0xD8121419);g.fill(panelLeft,panelTop,panelRight,panelTop+1,0xFF5D6775);g.fill(panelLeft,contentTop-5,panelRight,contentBottom+5,0x7A080A0E);for(int i=0;i<SECTION_STARTS[tab].length;i++){int start=SECTION_STARTS[tab][i],end=i+1<SECTION_STARTS[tab].length?SECTION_STARTS[tab][i+1]-1:rowCount()-1;int top=y(start)-SECTION_HEIGHT+2,bottom=y(end)+rowHeight();if(bottom>=contentTop&&top<=contentBottom){g.fill(panelLeft+10,Math.max(contentTop,top),panelRight-10,Math.min(contentBottom,bottom),0x50262B33);g.fill(panelLeft+10,Math.max(contentTop,top),panelLeft+12,Math.min(contentBottom,bottom),0xFF6E92B5);}}g.fill(panelLeft,panelBottom-41,panelRight,panelBottom,0xE51A1D23);}
 @Override public void extractRenderState(GuiGraphicsExtractor g,int mx,int my,float d){super.extractRenderState(g,mx,my,d);if(tab==2&&cachedFollowEntity!=FreeCameraClient.followTargetEntity())refreshFooterStatus();else if(tab==4&&!Objects.equals(cachedStudioStatus,studioStatus))refreshFooterStatus();g.centeredText(font,title,width/2,panelTop+8,0xFFFFFFFF);int tw=Math.max(48,(panelRight-panelLeft-24)/6),selectedX=panelLeft+12+tab*tw;g.fill(selectedX,panelTop+44,selectedX+tw-2,panelTop+46,0xFF6FA9DC);for(var entry:visibleLabels.entrySet())g.text(font,entry.getValue(),labelLeft,labelY(entry.getKey()),0xFFE2E5EA,false);for(int i=0;i<SECTION_STARTS[tab].length;i++){int sy=y(SECTION_STARTS[tab][i])-14;if(sy>=contentTop&&sy<contentBottom)g.text(font,SECTION_LABELS[tab][i],labelLeft,sy,0xFF8FC1EA,false);}g.text(font,footerStatus,panelLeft+14,panelBottom-43,footerStatusColor,false);}
}
