modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="freecamera"
version="${version}"
displayName="Free Camera"
description="Take full control of your camera: freecam, orbit, tripod lock, cinematic mode, roll, zoom, and more."
authors="Cukkoo"
logoFile=""
environment="CLIENT"

[[mixins]]
config="freecamera.mixins.json"
