package com.cukkoo.freecamera.recording;

import com.cukkoo.freecamera.api.CameraMode;import com.cukkoo.freecamera.api.CameraPose;import com.cukkoo.freecamera.path.*;
public final class StudioDevelopmentChecks{
 public static void main(String[]args){verifySampling();verifyPlayback();verifyPathEditing();verifyPathInterpolation();System.out.println("Recording and path timing, interpolation, editing, and limits checks passed.");}
 private static void verifySampling(){int reference=0;for(int fps:new int[]{10,20,30,60,144,240}){CameraRecording r=new CameraRecording();CameraRecordingSampler s=new CameraRecordingSampler();s.reset();for(int f=0;f<=fps;f++){double t=(double)f/fps;CameraPose p=new CameraPose(t*10,0,0,0,0);req(s.sample(r,p,t*360,1+t*2,CameraMode.FREE_CAMERA,t,30,1000),"sampling limit");}if(reference==0)reference=r.size();req(r.size()==reference&&r.size()==31,"FPS-dependent sampling");req(Math.abs(r.get(30).x()-10)<1e-8,"fixed sample interpolation");}}
 private static void verifyPlayback(){CameraRecording r=new CameraRecording();r.add(new CameraRecordingFrame(0,0,0,0,170,0,0,1,CameraMode.FREE_CAMERA),10);r.add(new CameraRecordingFrame(1,10,0,0,-170,0,360,3,CameraMode.FREE_CAMERA),10);CameraPlaybackController p=new CameraPlaybackController();CameraPose out=new CameraPose(0,0,0,0,0);p.play(r);p.apply(out,.25);p.apply(out,.25);req(Math.abs(out.x()-5)<1e-8,"playback position "+out.x());req(Math.abs(Math.abs(out.yaw())-180)<1e-5,"playback yaw "+out.yaw());p.pause();double t=p.time();p.apply(out,.2);req(p.time()==t,"pause advanced");}
 private static void verifyPathEditing(){CameraPath p=new CameraPath();CameraKeyframe a=k(0,0);CameraKeyframe b=k(10,90);p.add(a);p.add(b);p.duplicate(0);req(p.size()==3,"duplicate");p.move(2,0);p.remove(1);p.replace(0,a);req(p.size()==2,"path editing");}
 private static void verifyPathInterpolation(){CameraPath p=new CameraPath();p.add(k(0,170));p.add(k(10,-170));CameraPose out=new CameraPose(0,0,0,0,0);new CameraPathInterpolator().apply(p,0,0,out);req(out.x()==0,"first endpoint");new CameraPathInterpolator().apply(p,0,1,out);req(out.x()==10,"final endpoint");new CameraPathInterpolator().apply(p,0,.5,out);req(Math.abs(Math.abs(out.yaw())-180)<1e-5,"yaw wrap");}
 private static CameraKeyframe k(double x,float yaw){return new CameraKeyframe(x,0,0,yaw,0,x*36,1+x/10,1,PathEasing.LINEAR,0);}private static void req(boolean v,String m){if(!v)throw new AssertionError(m);}
}
