package com.cukkoo.freecamera.hud;
import com.cukkoo.freecamera.api.CameraMode;import com.cukkoo.freecamera.cinematic.CinematicMotionState;import com.cukkoo.freecamera.collision.CameraCollisionResolver;import com.cukkoo.freecamera.config.FreeCameraConfigManager;import com.cukkoo.freecamera.follow.FollowCameraRig;import com.cukkoo.freecamera.motion.CameraMotionIntegrator;import com.cukkoo.freecamera.orbit.OrbitCameraRig;import com.cukkoo.freecamera.path.CameraPathController;import com.cukkoo.freecamera.recording.CameraRecordingController;import com.cukkoo.freecamera.roll.CameraRollController;import com.cukkoo.freecamera.state.CameraStateMachine;import com.cukkoo.freecamera.zoom.CameraZoomController;import net.fabricmc.fabric.api.client.rendering.v1.hud.HudElementRegistry;import net.minecraft.client.Minecraft;import net.minecraft.client.gui.GuiGraphicsExtractor;import net.minecraft.network.chat.Component;import net.minecraft.resources.Identifier;
public final class CameraStatusHud{
 private static final Component HINTS=Component.literal("F6 Camera  •  F9 Cinematic  •  Z/C Roll  •  V Zoom  •  R Reset  •  G Follow Target");
 private final CameraStateMachine machine;private final FreeCameraConfigManager config;private final CameraMotionIntegrator motion;private final OrbitCameraRig orbit;private final FollowCameraRig follow;private final CameraCollisionResolver collision;private final CinematicMotionState cinematic;private final CameraRollController roll;private final CameraZoomController zoom;private final CameraRecordingController recording;private final CameraPathController path;
 private final Component[] lines=new Component[16];private int count;private long signature=Long.MIN_VALUE;
 public CameraStatusHud(CameraStateMachine m,FreeCameraConfigManager c,CameraMotionIntegrator motion,OrbitCameraRig orbit,FollowCameraRig follow,CameraCollisionResolver collision,CinematicMotionState cinematic,CameraRollController roll,CameraZoomController zoom,CameraRecordingController recording,CameraPathController path){this.machine=m;this.config=c;this.motion=motion;this.orbit=orbit;this.follow=follow;this.collision=collision;this.cinematic=cinematic;this.roll=roll;this.zoom=zoom;this.recording=recording;this.path=path;}
 public void register(){HudElementRegistry.addLast(Identifier.fromNamespaceAndPath("free-camera","camera_status"),this::render);}
 private void render(GuiGraphicsExtractor g,net.minecraft.client.DeltaTracker tracker){if(!machine.isActive())return;var c=config.config();if(c.letterbox){int h=(int)(g.guiHeight()*c.letterboxSize);g.fill(0,0,g.guiWidth(),h,0xE0000000);g.fill(0,g.guiHeight()-h,g.guiWidth(),g.guiHeight(),0xE0000000);}Minecraft mc=Minecraft.getInstance();boolean debug=c.hideStatusWithDebug&&mc.getDebugOverlay().showDebugScreen();if(c.controlHints&&!debug)g.centeredText(mc.font,HINTS,g.guiWidth()/2,g.guiHeight()-14,0xFFDDDDDD);if(!c.statusOverlay||debug)return;long next=signature();if(next!=signature){signature=next;rebuild();}int x=c.statusPosition.endsWith("RIGHT")?g.guiWidth()-154:6;int y=c.statusPosition.startsWith("BOTTOM")?g.guiHeight()-count*10-20:6;for(int i=0;i<count;i++)g.text(mc.font,lines[i],x,y+i*10,0xFFFFFFFF,true);}
 private long signature(){CameraMode mode=machine.activeModeOrNull();long s=mode.ordinal();s=s*31+q(roll.state().currentRoll());s=s*31+q(zoom.state().currentMultiplier());s=s*31+(cinematic.isEnabled()?1:0);s=s*31+(collision.state().isObstructed()?1:0);s=s*31+q(recording.recordingElapsed());s=s*31+recording.recordingSamples();s=s*31+q(recording.playback().time());s=s*31+q(path.time());s=s*31+(recording.playback().isLoop()?1:0)+(recording.playback().isReverse()?2:0);s=s*31+(path.isLoop()?1:0)+(path.isReverse()?2:0)+(path.isPingPong()?4:0);if(mode==CameraMode.ORBIT)s=s*31+q(orbit.requestedRadiusForMessage());if(mode==CameraMode.FOLLOW){s=s*31+follow.state().profile().ordinal();s=s*31+(follow.state().target()==null?0:follow.state().target().getId());}return s;}
 private void rebuild(){count=0;CameraMode mode=machine.activeModeOrNull();add("Mode: "+modeName(mode));if(mode==CameraMode.FREE_CAMERA)add("Speed: "+f(motion.displayedSpeed())+" b/s");if(mode==CameraMode.ORBIT){add("Requested Radius: "+f(orbit.requestedRadiusForMessage()));if(collision.state().isObstructed())add("Resolved Radius: "+f(distanceToPlayer()));}if(mode==CameraMode.FOLLOW){var target=follow.state().target();add("Target: "+(target==null?"None":target.getDisplayName().getString()));add("Profile: "+follow.state().profile());add("Requested Distance: "+f(follow.state().distance()));if(collision.state().isObstructed())add("Resolved Distance: "+f(distanceToFollow()));}add("Cinematic: "+(cinematic.isEnabled()?"On":"Off"));add("Collision: "+collisionMode(mode));add("Roll: "+f(roll.state().currentRoll())+"°");add("Zoom: "+f(zoom.state().currentMultiplier())+"×");if(recording.isRecording())add("Recording: "+f(recording.recordingElapsed())+"/"+config.config().recordingMaxSeconds+"s | "+recording.recordingSamples()+"/"+config.config().maximumRecordingSamples+" samples");if(recording.playback().isPlaying()){add("Recording "+recording.playback().name()+": "+playState(recording.playback().isPaused())+" "+f(recording.playback().time())+"/"+f(recording.playback().duration())+"s "+f(recording.playback().speed())+"×");add("Playback: "+flags(recording.playback().isLoop(),recording.playback().isReverse(),false)+(config.config().playbackCollision?(playbackAdjusted()?" | Collision adjusted":" | Collision clear"):" | Exact"));}if(path.isPlaying()){add("Path "+path.name()+": "+playState(path.isPaused())+" "+f(path.time())+"/"+f(path.duration())+"s "+f(path.speed())+"×");add("Playback: "+flags(path.isLoop(),path.isReverse(),path.isPingPong())+(config.config().playbackCollision?(playbackAdjusted()?" | Collision adjusted":" | Collision clear"):" | Exact"));}}
 private String collisionMode(CameraMode mode){var c=config.config();return String.valueOf(switch(mode){case ORBIT->c.orbitCollision;case FOLLOW->c.followCollision;case TRIPOD->com.cukkoo.freecamera.collision.CameraCollisionMode.OFF;case FREE_CAMERA->c.freeCollision;});}private static String flags(boolean loop,boolean reverse,boolean pingPong){return (loop?"Loop ":"")+(reverse?"Reverse ":"")+(pingPong?"Ping-pong":"");}
 private void add(String value){if(count<lines.length)lines[count++]=Component.literal(value);}private static String playState(boolean paused){return paused?"Paused":"Playing";}private static String modeName(CameraMode m){return switch(m){case FREE_CAMERA->"Free";case ORBIT->"Orbit";case TRIPOD->"Tripod";case FOLLOW->"Follow";};}private static long q(double v){return Math.round(v*10);}private static String f(double v){return String.format(java.util.Locale.ROOT,"%.1f",v);}private boolean playbackAdjusted(){var s=machine.activeSessionOrNull();if(s==null)return false;var a=s.pose();var b=s.renderedPose();double x=a.x()-b.x(),y=a.y()-b.y(),z=a.z()-b.z();return x*x+y*y+z*z>1e-10;}private double distanceToPlayer(){var p=Minecraft.getInstance().player;var pose=machine.activeSessionOrNull().renderedPose();return p==null?0:Math.sqrt(p.distanceToSqr(pose.x(),pose.y(),pose.z()));}private double distanceToFollow(){var pose=machine.activeSessionOrNull().renderedPose();double x=pose.x()-follow.anchorX(),y=pose.y()-follow.anchorY(),z=pose.z()-follow.anchorZ();return Math.sqrt(x*x+y*y+z*z);}
}
